### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [billthefarmer/sig-gen#18]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by billthefarmer** [comment]
I build apps for multiple platforms - Windows, MacOSX, Linux, Android and I keep the icons and general appearance of the apps as consistent  as possible. So I'm not going to change the icon of one app on one platform just because Google came up with a new wheeze.

**Comment by c-e-p-x-u-o** [comment]
sig-gen runs only on android!

**Comment by billthefarmer** [comment]
[Mac version](https://github.com/billthefarmer/audiotools/releases/tag/v1.03), [Windows](https://github.com/billthefarmer/audiotools/releases/tag/v1.01).

**Comment by 532910** [comment]
The fact that sig-gen runs on multiple platforms does not contradict to have an adaptive icon for android.

You need to split to into two components: foreground (wave) and background (grid).

**Comment by billthefarmer** [comment]
I have carefully crafted the icons for my apps so they work on different versions of android. The audio app icons work fine clipped to an oval rectangle or as they are, whereas the others have a non- square shape so they are shown in a white oval rectangle. Other developers have done something similar. If you look at the Crossword icon below, the grid lines stick out of the edges, to force it not to be clipped. Just because Google keep moving the goalposts, there's no reason to slavishly follow. For example they have just deprecated the whole settings API for no good reason that I can see. It works just fine.

![Screenshot_20201212-141000_One_UI_Home 1](https://user-images.githubusercontent.com/3448386/101986111-d6611100-3c83-11eb-97dc-3f35a26d1597.jpg)

**Comment by 532910** [comment]
In fact your icons looks ugly:
![image](https://user-images.githubusercontent.com/14617699/101989996-1096d680-3cb5-11eb-832e-8d2df36ac68b.png)

this is trebuchet launcher
