### ISSUE TITLE
Power usage

### ISSUE THREAD

**Issue by phmarek** [billthefarmer/sig-gen#36]
![siggen-power-usage](https://github.com/billthefarmer/sig-gen/assets/496570/ca508105-56e6-4241-9b51-95a202be1c19)

Using Signal Generator 1.30 (via FDroid) I noticed quite severe power usage -- see the attached screenshot.

Watching videos for 10 hours takes ~5% of the battery, but 2 mins of sig-gen 23%? I guess there's something amiss.
Do you re-calculate the waveform a million times a second or so?

**Comment by phmarek** [comment]
It's the slope going from ~60% to ~30%, BTW.

**Comment by billthefarmer** [comment]
I have checked this, the app does one calculation per sample. Assuming a sample rate of 44100, that's 44100 calculations per second. The code is very simple, it's here https://github.com/billthefarmer/sig-gen/blob/8e224fa3acfbcafc5459a8d94e9516809ec564a8/src/main/java/org/billthefarmer/siggen/Main.java#L1165
I tested on a ten year old Moto G that I use for testing my apps, first the battery use:

![Screenshot_20230608-141517 1](https://github.com/billthefarmer/sig-gen/assets/3448386/94c33252-2d69-4b9d-bd40-1a4fd262c699)

Profiler &ndash; Moto G:
![Moto G](https://github.com/billthefarmer/sig-gen/assets/3448386/c2945f1d-c4c3-45f2-af06-4541ee1aacd9)

It's using 24Mb of memory and negligible CPU.

Profiler &ndash; Pixel 3a
![Pixel 3a](https://github.com/billthefarmer/sig-gen/assets/3448386/1363e371-ea07-4a26-9e20-700df5feece5)

It's using about 48Mb of memory and no measurable CPU. If you have the phone speaker on that will use more power, otherwise you appear to have a problem.

**Comment by phmarek** [comment]
Perhaps that's been a fluke in LineageOS - either measuring or attributing the power usage, or somehow running some sig-gen code in an unexpected loop (calling intents all the time)?

Can't reproduce now.

Thanks!
